name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: ./slide

      - name: Build slides
        run: bun run build:pages
        working-directory: ./slide

      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./slide/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
